openapi: 3.0.0
info:
  title: Common schema
  version: '1.0'
paths: {}
components:
  responses:
    BadRequest:
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: "./common_response_schema.yaml#/components/schemas/BadRequestErrorResponseBody"