openapi: 3.0.0
info:
  title: Order API
  version: '1.0'
servers:
  - url: http://localhost:8080
tags:
  - name: WIP
    description: API still under development
paths:
  /findAvailableProducts:
    parameters:
      - schema:
          type: string
        name: type
        in: query
        required: false
        examples:
          SUCCESS:
            value: gadget
          TIMEOUT:
            value: other
      - name: pageSize
        in: header
        schema:
          type: integer
        required: true
        examples:
          SUCCESS:
            value: 10
          TIMEOUT:
            value: 20
    get:
      summary: Fetch product details
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                SUCCESSFUL:
                  value:
                    - name: iPhone
                      id: 1
                      type: gadget
                      inventory: 100

components:
  schemas:
    Product:
      title: Product Details
      type: object
      properties:
        name:
          type: string
        id:
          type: integer
        type:
          type: string
        inventory:
          type: integer
        description:
          type: string
      required:
        - name
        - id
        - type
        - inventory
    BadRequest:
      title: Bad Request
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: number
        error:
          type: string
        message:
          type: string