name: Lint specifications and check Backward Compatibility

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
   run-lint:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0

       - name: Set up Git
         run: |
           git fetch origin main
           git branch --set-upstream-to=origin/main main

       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '14'

       - name: Install OpenAPI linter
         run: npm install -g @stoplight/spectral-cli

       - name: Lint OpenAPI specs
         run: spectral lint **/*.yaml

       - name: Create environment file
         run: |
           # echo "GITHUB_REF=${{ github.ref }}" >> env.list
           echo "GITHUB_SHA=${{ github.sha }}" >> env.list
           echo "GITHUB_REPOSITORY=${{ github.repository }}" >> env.list
           echo "GITHUB_ACTOR=${{ github.actor }}" >> env.list
           echo "GITHUB_WORKFLOW=${{ github.workflow }}" >> env.list
           echo "GITHUB_HEAD_REF=${{ github.head_ref }}" >> env.list
           if [ -z "${{ github.base_ref }}" ]; then
               echo "GITHUB_BASE_REF=${{ github.ref }}" | sed 's/refs\/heads\///' >> env.list
           else
             echo "GITHUB_BASE_REF=${{ github.base_ref }}" >> env.list
           fi

       - name: Run OpenAPI Examples validation check
         run: |
           docker run -v "$(pwd):/central-contract-repo:rw" znsio/specmatic examples validate \
           --contract-file /central-contract-repo/orders/product_search_bff_v4.yaml

       - name: Run OpenAPI backward compatibility check
         run: |
           docker run -v "$(pwd):/central-contract-repo:rw" znsio/specmatic backward-compatibility-check \
           --base-branch origin/main
