name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check API Contracts
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Get changed yaml files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.yaml
            **/*.yml
            **/*.json
          files_ignore: | 
            kafka.yaml 
            .github/workflows/*.yml

      - name: Install Spectral Linter
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: npm install -g @stoplight/spectral-cli

      - name: Run Spectral linter on changed files
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "Running Spectral linter on: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
          spectral lint io/**/*.yaml

      - name: new step
        run: |
          echo "any changed: ${{steps.changed-files-specific.outputs.any_changed}}"
          echo "${{steps.changed-files-specific.outputs.all_changed_files}}"
          echo "any modified: ${{steps.changed-files-specific.outputs.any_modified}}"
          echo "${{steps.changed-files-specific.outputs.all_modified_files}}"

      - name: Run OpenAPI backward compatibility check on changed files
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          docker run -v "$(pwd):/central-contract-repo:rw" \
            --entrypoint /bin/sh znsio/specmatic \
            -c "git config --global --add safe.directory /central-contract-repo && cd /central-contract-repo && java -jar /usr/src/app/specmatic.jar backward-compatibility-check --base-branch origin/main"

      - name: Run OpenAPI Examples validation check
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          docker run -v "$(pwd):/central-contract-repo:rw" znsio/specmatic examples validate \
           --contract-file /central-contract-repo/orders/product_search_bff_v4.yaml

      - name: Generate central contract repo report
        run: |
            docker run -v "$(pwd):/central-contract-repo:rw" \
            --entrypoint /bin/sh znsio/specmatic \
            -c "cd /central-contract-repo && java -jar /usr/src/app/specmatic.jar central-contract-repo-report"

            - name: Run Specmatic Insights Github Build Reporter
              uses: znsio/specmatic-insights-build-reporter-github-action@v2.0.2
              with:
                github-token: ${{ secrets.GH_REPOSITORY_TOKEN }}
                org-id: 66fe6c555e232d36a28fef94
                branch-ref: ${{ github.ref }}
                branch-name: ${{ github.ref_name }}
                build-id: ${{ github.run_id }}
                repo-name: ${{ github.event.repository.name }}
                repo-id: ${{ github.repository_id }}
                repo-url: ${{ github.event.repository.html_url }}